### ISSUE TITLE
Sometimes browserify munges the emoji

### ISSUE THREAD

**Issue by toddself** [choojs/nanologger#3]
From my bundle:

```js
},{"./support/isBuffer":37,"_process":35,"inherits":36}],39:[function(require,module,exports){
var emojis = {
  debug: 'ðŸ›',
  info: 'âœ¨',
  warn: 'âš ï¸',
  error: 'ðŸš¨',
  fatal: 'ðŸ’€'
}
```

But the source map version has them _fine_.

This is a placeholder issue -- i need to debug this more!

**Comment by yoshuawuyts** [comment]
@toddself found anything?

**Comment by toddself** [comment]
I found I have a great family who planned an awesome father's day?

Oh, about this bug?  LOL.

We think it might be babel.  I haven't had a proper amount of time to sit down and see what exactly is going on with our miasma of options and transforms.  Adding this to my task list for the week though!

**Comment by yoshuawuyts** [comment]
Haha, yay for family! :D

**Comment by toddself** [comment]
This isn't an issue with nanologger, closing

**Comment by Frando** [comment]
I'm having the same problems - weird characters instead of emojis in the chromium console. Any clues on what to do?
I'm using browserify and babelify.

**Comment by yoshuawuyts** [comment]
Hey! Sorry to hear that. Do you perhaps have a screenshot, node version,
choo version and choo-log - thanks!
